@host=https://localhost:5001

###
# @name machines
GET {{host}}/api/machines
Accept: application/json

###
@firstMachine={{machines.response.body.$.[0].id}}
GET {{host}}/api/machines/{{firstMachine}}
Accept: application/json

###
POST {{host}}/api/machines
Accept: application/json
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Foo",
  "imageUrl": "bar.jpg",
  "description": "Foo Bar"
}

###
@firstMachine={{machines.response.body.$.[0].id}}
DELETE {{host}}/api/machines/{{firstMachine}}
