@host=https://localhost:5001

###
# @name machines
GET {{host}}/api/machines
Accept: application/json

###
@firstMachine={{machines.response.body.$.[0].id}}
GET {{host}}/api/machines/{{firstMachine}}
Accept: application/json

###
@firstMachine={{machines.response.body.$.[0].id}}
GET {{host}}/api/machines/{{firstMachine}}/image
Accept: application/json

###
POST {{host}}/api/machines
Accept: application/json
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Foo",
  "imageUrl": "bar.jpg",
  "description": "Foo Bar"
}

###
@firstMachine={{machines.response.body.$.[0].id}}
DELETE {{host}}/api/machines/{{firstMachine}}

###
@firstMachine={{machines.response.body.$.[0].id}}
GET {{host}}/api/machines/{{firstMachine}}/settings
Accept: application/json

###
@firstMachine={{machines.response.body.$.[0].id}}
GET {{host}}/api/machines/{{firstMachine}}/switches
Accept: application/json

###
@firstMachine={{machines.response.body.$.[0].id}}
PUT {{host}}/api/machines/{{firstMachine}}/settings
Accept: application/json
Content-Type: application/json

[
  {
    "id": "{{$guid}}",
    "name": "Setting 1",
    "description": "Description Setting 1",
    "value": 33.484,
    "positionX": 10,
    "positionY": 480
  },
  {
    "id": "{{$guid}}",
    "name": "Setting 2",
    "description": "Description Setting 2",
    "value": 5.8,
    "positionX": 120,
    "positionY": 40
  }
]

###
@firstMachine={{machines.response.body.$.[0].id}}
PUT {{host}}/api/machines/{{firstMachine}}/switch
Accept: application/json
Content-Type: application/json

{
  "id": "{{$guid}}",
  "value": true
}

###
https://demo.identityserver.io/connect/userinfo
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkVCQTRGRDNDRUExMDREOTlBODkwODkyNEJBMjNDMEYwIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDU4NTQ4MDksImV4cCI6MTYwNTg1ODQwOSwiaXNzIjoiaHR0cHM6Ly9kZW1vLmlkZW50aXR5c2VydmVyLmlvIiwiY2xpZW50X2lkIjoiaW50ZXJhY3RpdmUuY29uZmlkZW50aWFsIiwic3ViIjoiMTEiLCJhdXRoX3RpbWUiOjE2MDU4NTM2NzIsImlkcCI6ImxvY2FsIiwianRpIjoiNEY4NTkxODA2RUIzRTNBRUJDQkMzMDE1NkVBMTc1OTYiLCJzaWQiOiI5REFGNjE1MkYxQUFDNEY5MkNCMjBBQTJCNEU0Mjk0MiIsImlhdCI6MTYwNTg1NDgwOSwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIl0sImFtciI6WyJwd2QiXX0.wxmY3XvAsnDY2n5Jm7dpF3OpvF63MDaARkXrLfn5yNMk4EPRaP8L51Rdu7G34lGdu0Gp-g81PbnmWKssVujlTnSuOJL0GKxMpK1sc8TVBv2maOiyXiGMp5Qfs2vZQG9OiNtpuP-mlCzX0XZFlgoSq2jOs6_OvOPU2jT_JlYSRu9wyPKzaXjLvluRj-N_RVvF7isHzAO2eqGwHPw7mDm4k-PybLywbiRJddDjFPazCXzRkoeltDN3AHU3XGYRsQQ88F0dyIaF6dI2ox4PMYh0mnxzHBoKjeBaV3iTptAm4TCekT0av4kBUodCOhRUQ7g8SBiQ11awFHoCntiN2jmdgg
