/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as Parameters from "./models/parameters";
import { NetCoreMicroserviceSampleApiContext } from "./netCoreMicroserviceSampleApiContext";

class NetCoreMicroserviceSampleApi extends NetCoreMicroserviceSampleApiContext {
  /**
   * Initializes a new instance of the NetCoreMicroserviceSampleApi class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.NetCoreMicroserviceSampleApiOptions) {
    super(options);
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  login(options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param callback The callback
   */
  login(callback: msRest.ServiceCallback<void>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  login(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  login(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      loginOperationSpec,
      callback);
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  logout(options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param callback The callback
   */
  logout(callback: msRest.ServiceCallback<void>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  logout(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  logout(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      logoutOperationSpec,
      callback);
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.GetProfileResponse>
   */
  getProfile(options?: msRest.RequestOptionsBase): Promise<Models.GetProfileResponse>;
  /**
   * @param callback The callback
   */
  getProfile(callback: msRest.ServiceCallback<any>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  getProfile(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  getProfile(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.GetProfileResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      getProfileOperationSpec,
      callback) as Promise<Models.GetProfileResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.GetHealthResponse>
   */
  getHealth(options?: msRest.RequestOptionsBase): Promise<Models.GetHealthResponse>;
  /**
   * @param callback The callback
   */
  getHealth(callback: msRest.ServiceCallback<string>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  getHealth(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<string>): void;
  getHealth(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<string>, callback?: msRest.ServiceCallback<string>): Promise<Models.GetHealthResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      getHealthOperationSpec,
      callback) as Promise<Models.GetHealthResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.GetAllMachinesResponse>
   */
  getAllMachines(options?: msRest.RequestOptionsBase): Promise<Models.GetAllMachinesResponse>;
  /**
   * @param callback The callback
   */
  getAllMachines(callback: msRest.ServiceCallback<Models.MachineMetadata[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  getAllMachines(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.MachineMetadata[]>): void;
  getAllMachines(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.MachineMetadata[]>, callback?: msRest.ServiceCallback<Models.MachineMetadata[]>): Promise<Models.GetAllMachinesResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      getAllMachinesOperationSpec,
      callback) as Promise<Models.GetAllMachinesResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.AddMachineResponse>
   */
  addMachine(options?: Models.NetCoreMicroserviceSampleApiAddMachineOptionalParams): Promise<Models.AddMachineResponse>;
  /**
   * @param callback The callback
   */
  addMachine(callback: msRest.ServiceCallback<Models.Machine>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  addMachine(options: Models.NetCoreMicroserviceSampleApiAddMachineOptionalParams, callback: msRest.ServiceCallback<Models.Machine>): void;
  addMachine(options?: Models.NetCoreMicroserviceSampleApiAddMachineOptionalParams | msRest.ServiceCallback<Models.Machine>, callback?: msRest.ServiceCallback<Models.Machine>): Promise<Models.AddMachineResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      addMachineOperationSpec,
      callback) as Promise<Models.AddMachineResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.UpdateMachineResponse>
   */
  updateMachine(options?: Models.NetCoreMicroserviceSampleApiUpdateMachineOptionalParams): Promise<Models.UpdateMachineResponse>;
  /**
   * @param callback The callback
   */
  updateMachine(callback: msRest.ServiceCallback<any>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  updateMachine(options: Models.NetCoreMicroserviceSampleApiUpdateMachineOptionalParams, callback: msRest.ServiceCallback<any>): void;
  updateMachine(options?: Models.NetCoreMicroserviceSampleApiUpdateMachineOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.UpdateMachineResponse> {
    return this.sendOperationRequest(
      {
        options
      },
      updateMachineOperationSpec,
      callback) as Promise<Models.UpdateMachineResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.MachineByIdResponse>
   */
  machineById(id: string, options?: msRest.RequestOptionsBase): Promise<Models.MachineByIdResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  machineById(id: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  machineById(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  machineById(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.MachineByIdResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      machineByIdOperationSpec,
      callback) as Promise<Models.MachineByIdResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.DeleteMachineResponse>
   */
  deleteMachine(id: string, options?: msRest.RequestOptionsBase): Promise<Models.DeleteMachineResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  deleteMachine(id: string, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMachine(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  deleteMachine(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ProblemDetails>, callback?: msRest.ServiceCallback<Models.ProblemDetails>): Promise<Models.DeleteMachineResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      deleteMachineOperationSpec,
      callback) as Promise<Models.DeleteMachineResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.GetMachineImageResponse>
   */
  getMachineImage(id: string, options?: msRest.RequestOptionsBase): Promise<Models.GetMachineImageResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  getMachineImage(id: string, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  getMachineImage(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  getMachineImage(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ProblemDetails>, callback?: msRest.ServiceCallback<Models.ProblemDetails>): Promise<Models.GetMachineImageResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      getMachineImageOperationSpec,
      callback) as Promise<Models.GetMachineImageResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.GetMachineSettingsResponse>
   */
  getMachineSettings(id: string, options?: msRest.RequestOptionsBase): Promise<Models.GetMachineSettingsResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  getMachineSettings(id: string, callback: msRest.ServiceCallback<Models.MachineSetting[]>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  getMachineSettings(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.MachineSetting[]>): void;
  getMachineSettings(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.MachineSetting[]>, callback?: msRest.ServiceCallback<Models.MachineSetting[]>): Promise<Models.GetMachineSettingsResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      getMachineSettingsOperationSpec,
      callback) as Promise<Models.GetMachineSettingsResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.UpdateMachineSettingsResponse>
   */
  updateMachineSettings(id: string, options?: Models.NetCoreMicroserviceSampleApiUpdateMachineSettingsOptionalParams): Promise<Models.UpdateMachineSettingsResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  updateMachineSettings(id: string, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  updateMachineSettings(id: string, options: Models.NetCoreMicroserviceSampleApiUpdateMachineSettingsOptionalParams, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  updateMachineSettings(id: string, options?: Models.NetCoreMicroserviceSampleApiUpdateMachineSettingsOptionalParams | msRest.ServiceCallback<Models.ProblemDetails>, callback?: msRest.ServiceCallback<Models.ProblemDetails>): Promise<Models.UpdateMachineSettingsResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      updateMachineSettingsOperationSpec,
      callback) as Promise<Models.UpdateMachineSettingsResponse>;
  }

  /**
   * @param id
   * @param [options] The optional parameters
   * @returns Promise<Models.GetMachineSwitchesResponse>
   */
  getMachineSwitches(id: string, options?: msRest.RequestOptionsBase): Promise<Models.GetMachineSwitchesResponse>;
  /**
   * @param id
   * @param callback The callback
   */
  getMachineSwitches(id: string, callback: msRest.ServiceCallback<Models.MachineSwitch[]>): void;
  /**
   * @param id
   * @param options The optional parameters
   * @param callback The callback
   */
  getMachineSwitches(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.MachineSwitch[]>): void;
  getMachineSwitches(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.MachineSwitch[]>, callback?: msRest.ServiceCallback<Models.MachineSwitch[]>): Promise<Models.GetMachineSwitchesResponse> {
    return this.sendOperationRequest(
      {
        id,
        options
      },
      getMachineSwitchesOperationSpec,
      callback) as Promise<Models.GetMachineSwitchesResponse>;
  }

  /**
   * @param id
   * @param switchId
   * @param [options] The optional parameters
   * @returns Promise<Models.SetMachineSwitchResponse>
   */
  setMachineSwitch(id: string, switchId: string, options?: msRest.RequestOptionsBase): Promise<Models.SetMachineSwitchResponse>;
  /**
   * @param id
   * @param switchId
   * @param callback The callback
   */
  setMachineSwitch(id: string, switchId: string, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  /**
   * @param id
   * @param switchId
   * @param options The optional parameters
   * @param callback The callback
   */
  setMachineSwitch(id: string, switchId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ProblemDetails>): void;
  setMachineSwitch(id: string, switchId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ProblemDetails>, callback?: msRest.ServiceCallback<Models.ProblemDetails>): Promise<Models.SetMachineSwitchResponse> {
    return this.sendOperationRequest(
      {
        id,
        switchId,
        options
      },
      setMachineSwitchOperationSpec,
      callback) as Promise<Models.SetMachineSwitchResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const loginOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/Auth/login",
  responses: {
    200: {},
    default: {}
  },
  serializer
};

const logoutOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/Auth/logout",
  responses: {
    200: {},
    default: {}
  },
  serializer
};

const getProfileOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/Auth/profile",
  responses: {
    200: {
      bodyMapper: Mappers.UserProfile
    },
    401: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const getHealthOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/health",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const getAllMachinesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/machines",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "MachineMetadata"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const addMachineOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/machines",
  requestBody: {
    parameterPath: [
      "options",
      "body"
    ],
    mapper: Mappers.Machine
  },
  responses: {
    201: {
      bodyMapper: Mappers.Machine
    },
    default: {}
  },
  serializer
};

const updateMachineOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/machines",
  requestBody: {
    parameterPath: [
      "options",
      "body"
    ],
    mapper: Mappers.Machine
  },
  responses: {
    200: {
      bodyMapper: Mappers.Machine
    },
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const machineByIdOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/machines/{id}",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: Mappers.MachineMetadata
    },
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const deleteMachineOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/machines/{id}",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    204: {},
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const getMachineImageOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/machines/{id}/image",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {},
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const getMachineSettingsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/machines/{id}/settings",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "MachineSetting"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const updateMachineSettingsOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/machines/{id}/settings",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: [
      "options",
      "body"
    ],
    mapper: {
      serializedName: "body",
      type: {
        name: "Sequence",
        element: {
          type: {
            name: "Composite",
            className: "MachineSettingsUpdateDto"
          }
        }
      }
    }
  },
  responses: {
    200: {},
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

const getMachineSwitchesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/machines/{id}/switches",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "MachineSwitch"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const setMachineSwitchOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/machines/{id}/switches/{switchId}",
  urlParameters: [
    Parameters.id,
    Parameters.switchId
  ],
  responses: {
    200: {},
    404: {
      bodyMapper: Mappers.ProblemDetails
    },
    default: {}
  },
  serializer
};

export {
  NetCoreMicroserviceSampleApi,
  NetCoreMicroserviceSampleApiContext,
  Models as NetCoreMicroserviceSampleApiModels,
  Mappers as NetCoreMicroserviceSampleApiMappers
};
