name: Build Microservice Demo App (Machine)

on:
  push:
    branches:
      - main
    paths-ignore:
      - "NetCoreMicroserviceSample/NetCoreMicroserviceSample.Api/**"
      - "NetCoreMicroserviceSample/NetCoreMicroserviceSample.UserInterface/**"
env:
  MACHINE_PATH: './NetCoreMicroserviceSample/NetCoreMicroserviceSample.Machine'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.MACHINE_PATH }}/..
        file: ${{ env.MACHINE_PATH }}/Dockerfile
        push: true
        tags: rstropek/net-core-microservice-sample-machine:latest
